version: '3.7'
services:
  nginx:
    build: .
    image: ragedunicorn/nginx:${NGINX_TAG_VERSION}-stable
    ports:
      - "80:80"
    labels:
      com.ragedunicorn.nginx.environment: "prod"
      com.ragedunicorn.nginx.description: "Nginx container"
