version: '3.7'
services:
  nginx:
    build: .
    image: ragedunicorn/nginx:${NGINX_TAG_VERSION}-dev
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    labels:
      com.ragedunicorn.nginx.environment: "dev"
      com.ragedunicorn.nginx.description: "Nginx container"
