version: '3.7'
services:
  nginx:
    build: .
    image: ragedunicorn/nginx:${NGINX_TAG_VERSION}-stable
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.nginx.environment: "prod"
      com.ragedunicorn.nginx.description: "Nginx container"
